name = "Folium"
description = "A simple application that uses pandas and folium to draw heatmaps on a map."
packages = [
  numpy,
  matplotlib
]
files = [
  "pyscripts/inventory.py",
  "pyscripts/constant.py",
  "pyscripts/plot.py"
]