 def calculate_Profit(PrA_0, PrA_1, PrA_2, PrA_3, PrA_4, P_A, PrB_0, PrB_1, PrB_2, PrB_3, PrB_4, P_B):
    """
    Calculate the largets profit generated by 4 trucks dispatched to different locations.

    Parameters:
        PrA_0 (float): Probability(n = 0) for a truck going to location A.
        PrA_1 (float): Probability(n = 1) for a truck going to location A.
        PrA_2 (float): Probability(n = 2) for a truck going to location A.
        PrA_3 (float): Probability(n = 3) for a truck going to location A.
        PrA_4 (float): Probability(n = 4) for a truck going to location A.
        P_A (int): Profit generated by each truck going to location A.
        PrB_0 (float): Probability(n = 0) for a truck going to location B.
        PrB_1 (float): Probability(n = 1) for a truck going to location B.
        PrB_2 (float): Probability(n = 2) for a truck going to location B.
        PrB_3 (float): Probability(n = 3) for a truck going to location B.
        PrB_4 (float): Probability(n = 4) for a truck going to location B.
        P_B (int): Profit generated by each truck going to location B.
    Returns: 
        float: the profit generated by trucks dispatched to A and trucks dispatched to B.
    """
    
    # Profit for 0 trucks to A and 4 trucks to B
    profit_0_A_4_B = P_B * {(1 - PrB_0) + (1 - PrB_0 - PrB_1) + (1 - PrB_0 - PrB_1 - PrB_2) + (1 - PrB_0 - PrB_1 - PrB_2 - PrB_3)}

    # Profit for 1 truck to A and 3 trucks to B
    profit_1_A_3_B = P_A * (1 - PrA_0) + P_B * {(1 - PrB_0) + (1 - PrB_0 - PrB_1) + (1 - PrB_0 - PrB_1 - PrB_2)}
    
    # Profit for 2 trucks to A and 2 trucks to B
    profit_2_A_2_B = P_A * {(1 - PrA_0) + (1 - PrA_0 - PrA_1)} + P_B * {(1 - PrB_0) + (1 - PrB_0 - PrB_1)}

    # Profit for 3 trucks to A and 1 truck to B
    profit_3_A_1_B = P_A * {(1 - PrA_0) + (1 - PrA_0 - PrA_1) + (1 - PrA_0 - PrA_1 - PrA_2)} + P_B * (1 - PrB_0)

    # Profit for 4 trucks to A and 0 trucks to B
    profit_4_A_0_B = P_A * {(1 - PrA_0) + (1 - PrA_0 - PrA_1) + (1 - PrA_0 - PrA_1 - PrA_2) + (1 - PrA_0 - PrA_1 - PrA_2 - PrA_3)}

    profits = [profit_0_A_4_B, profit_1_A_3_B, profit_2_A_2_B, profit_3_A_1_B, profit_4_A_0_B]

    max_profit = max(profits)

    return max(profits)

    print(f"Profit generated: {max_profit}")
